version: '3'

services:
  weddingdb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789aA
    ports:
      - "43:3306"

  wedding-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - weddingdb
    restart: always
    ports:
      - "80:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://weddingdb.mysql.database.azure.com:3306/wedding_platform?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=weddingroot
      - SPRING_DATASOURCE_PASSWORD=123456789aA